name: square_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - openimageio
  - pip
  - pip:
    - Qt.py
    - PyQt6
    - gazu
    - requests
    - pillow
    - xxhash
    - imageio-ffmpeg
    - ffmpeg-python
    - pyyaml
